version: '3.1'

services:
  web:
    image: nginx:alpine
    depends_on:
          - php
    restart: always
    volumes:
     - ./data/html:/var/www/html
     - ./data/nginx:/etc/nginx/conf.d
     - ./data/logs:/var/log/nginx
    ports:
     - "4444:80"

  php:
    build: ./data/php_docker/
    container_name: "php"
    depends_on:
          - mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      DB_HOST: mysql
      DB_NAME: wordpress
      DB_USER: wp-user
      DB_PASSWORD: wp-pass
      WORDPRESS_TABLE_PREFIX: wp_

    volumes:
     - ./data/html:/var/www/html
     - ./data/conf.d:/usr/local/etc/php/conf.d 

  mysql:
    image: mariadb
    restart: always
    volumes:
         - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp-pass


  adminer:
    image: adminer
    restart: always
    ports:
      - 5555:8080

